### ISSUE TITLE
Alternate half points mode

### ISSUE THREAD

**Issue by PolarTBear** [jimbali/eagsmaster#28]
To even out the swing of 0-10 points which can be high, have an optional alternate scoring mode of 1-5 points, with top 1 and 2 being 1 point, top 3 and 4 being 2 points etc

**Comment by jimbali** [comment]
The quiz host assigns the points themselves, so this will be possible when I add subzero points support: #26

**Comment by jimbali** [comment]
Actually I misunderstood, in fact this is already possible :)
